import { useState } from 'react';

// EDIT THIS before deploying — point it at your actual repo.
const GITHUB_URL = 'https://github.com/YOUR_USERNAME/datalens';

export default function TopBar() {
  const [aboutOpen, setAboutOpen] = useState(false);

  return (
    <nav className="topbar">
      <div className="topbar-about-wrap">
        <button className="topbar-link" onClick={() => setAboutOpen((o) => !o)}>
          About
        </button>
        {aboutOpen && (
          <div className="about-popover">
            <p>
              DataLens analyzes any tabular CSV or Excel file — auto-detecting columns,
              computing KPIs, and ranking findings by statistical significance.
            </p>
            <p className="dim-sub" style={{ marginTop: 8 }}>
              Built with React, FastAPI, and pandas. No AI/LLM calls — every
              finding is generated by a rule-based scoring engine, which keeps
              it free to run and safe to share publicly.
            </p>
          </div>
        )}
      </div>
      <a className="topbar-link" href={GITHUB_URL} target="_blank" rel="noreferrer">
        GitHub ↗
      </a>
    </nav>
  );
}
