"""
PDF report generation.

Stateless by design, matching the rest of the app: takes the same `v2`
analysis payload the frontend already has in memory (nothing is stored
server-side, no session, no re-upload needed) and renders it into a
downloadable PDF via reportlab. Mirrors the sheet layout of the Excel
export (exportReport.js) so the two outputs tell the same story in two
formats, just one built client-side and one server-side.
"""
import io
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

INK = colors.HexColor("#0A0A0B")
MUTED = colors.HexColor("#6B6B70")
BORDER = colors.HexColor("#DADADD")
RED = colors.HexColor("#C1272D")
SURFACE = colors.HexColor("#F5F5F6")


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(
        name="ReportTitle", fontSize=22, leading=26, spaceAfter=4,
        textColor=INK, fontName="Helvetica-Bold",
    ))
    ss.add(ParagraphStyle(
        name="ReportSubtitle", fontSize=10.5, leading=14, spaceAfter=18,
        textColor=MUTED, fontName="Helvetica",
    ))
    ss.add(ParagraphStyle(
        name="SectionHeading", fontSize=14, leading=18, spaceBefore=18,
        spaceAfter=8, textColor=INK, fontName="Helvetica-Bold",
    ))
    ss.add(ParagraphStyle(
        name="Body", fontSize=10, leading=14.5, textColor=INK,
        fontName="Helvetica", spaceAfter=6,
    ))
    ss.add(ParagraphStyle(
        name="BodyMuted", fontSize=9, leading=13, textColor=MUTED,
        fontName="Helvetica", spaceAfter=6,
    ))
    ss.add(ParagraphStyle(
        name="Caveat", fontSize=8.5, leading=12, textColor=RED,
        fontName="Helvetica-Oblique", spaceAfter=4,
    ))
    ss.add(ParagraphStyle(
        name="Cell", fontSize=8.5, leading=11.5, textColor=INK,
        fontName="Helvetica",
    ))
    return ss


def _cell(text, ss):
    """Wrap a table cell's text in a Paragraph so long text actually wraps
    within its column instead of overflowing into the next one -- plain
    strings in reportlab Table cells don't wrap on their own."""
    return Paragraph(str(text) if text is not None else "", ss["Cell"])


def _table(rows, col_widths, styles, header=True):
    """Small helper: rows is a list of lists of plain strings/Paragraphs."""
    t = Table(rows, colWidths=col_widths, repeatRows=1 if header else 0)
    style_cmds = [
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
    ]
    if header:
        style_cmds += [
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, 0), (-1, 0), INK),
            ("BACKGROUND", (0, 0), (-1, 0), SURFACE),
        ]
    t.setStyle(TableStyle(style_cmds))
    return t


def build_pdf_report(file_name: str, v2: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )
    ss = _styles()
    story = []

    # --- Cover / overview ---
    profile = v2.get("profile", {}) or {}
    story.append(Paragraph("DataLens Report", ss["ReportTitle"]))
    story.append(Paragraph(f"{file_name} &nbsp;·&nbsp; generated by DataLens", ss["ReportSubtitle"]))

    overview_rows = [["Field", "Value"]]
    for label, key in [
        ("Detected domain", "domain"),
        ("Domain confidence", "domain_confidence"),
        ("Primary entity", "primary_entity"),
        ("Row count", "row_count"),
        ("Column count", "column_count"),
        ("Data completeness", "data_completeness_pct"),
    ]:
        val = profile.get(key)
        if val is not None:
            overview_rows.append([label, str(val)])
    dq = v2.get("data_quality") or {}
    if dq.get("overall_quality_score") is not None:
        overview_rows.append(["Data quality score", str(dq["overall_quality_score"])])

    story.append(_table(overview_rows, [2.2 * inch, 3.3 * inch], ss))

    # --- Story ---
    beats = v2.get("story") or []
    if beats:
        story.append(Paragraph("The Story", ss["SectionHeading"]))
        for b in beats:
            label = b.get("label", "")
            text = b.get("text", "")
            if label:
                story.append(Paragraph(f"<b>{label}</b>", ss["Body"]))
            story.append(Paragraph(text, ss["Body"]))

    # --- Findings ---
    findings = v2.get("findings") or []
    if findings:
        story.append(Paragraph("Findings", ss["SectionHeading"]))
        rows = [["Finding", "Category"]]
        for f in findings:
            rows.append([_cell(f.get("text", ""), ss), _cell(f.get("category", ""), ss)])
        story.append(_table(rows, [4.3 * inch, 1.2 * inch], ss))

    # --- Weak points ---
    weak_points = v2.get("weak_points") or []
    if weak_points:
        story.append(PageBreak())
        story.append(Paragraph("Weak Points & Recommendations", ss["SectionHeading"]))
        for w in weak_points:
            priority = w.get("priority", "")
            story.append(Paragraph(f"<b>{w.get('problem', '')}</b> &nbsp;<font color='#6B6B70' size=8>[{priority}]</font>", ss["Body"]))
            if w.get("impact"):
                story.append(Paragraph(f"Impact: {w['impact']}", ss["BodyMuted"]))
            if w.get("suggested_action"):
                story.append(Paragraph(f"Suggested action: {w['suggested_action']}", ss["BodyMuted"]))
            story.append(Spacer(1, 6))

    # --- Data quality detail ---
    if dq:
        story.append(Paragraph("Data Quality", ss["SectionHeading"]))
        summary_rows = [["Metric", "Value"]]
        for label, key in [
            ("Duplicate rows", "duplicate_row_count"),
            ("Duplicate row %", "duplicate_row_pct"),
            ("Overall quality score (raw file)", "overall_quality_score"),
            ("Usable data score (analyzed columns)", "usable_quality_score"),
        ]:
            if dq.get(key) is not None:
                summary_rows.append([label, str(dq[key])])
        if dq.get("usable_column_count") is not None and dq.get("total_column_count") is not None:
            summary_rows.append(["Columns actually analyzed", f"{dq['usable_column_count']} of {dq['total_column_count']}"])
        const_cols = dq.get("constant_columns") or []
        if const_cols:
            summary_rows.append(["Constant columns", ", ".join(const_cols)])
        story.append(_table(summary_rows, [2.2 * inch, 3.3 * inch], ss))

        missing = dq.get("missing_by_column") or []
        if missing:
            story.append(Spacer(1, 10))
            story.append(Paragraph("Missing values by column", ss["Body"]))
            rows = [["Column", "Missing %"]] + [
                [_cell(m.get("column", ""), ss), _cell(m.get("missing_pct", ""), ss)] for m in missing
            ]
            story.append(_table(rows, [3.3 * inch, 2.2 * inch], ss))

    # --- Correlations ---
    cc = v2.get("correlation_center") or {}
    pairs = cc.get("pairs") or []
    if pairs:
        story.append(PageBreak())
        story.append(Paragraph("Correlation Center", ss["SectionHeading"]))
        rows = [["Columns", "r", "n", "p-value", "Significant", "Strength"]]
        for p in pairs:
            rows.append([
                _cell(f"{p.get('col1', '')} <-> {p.get('col2', '')}", ss),
                str(p.get("r", "")),
                str(p.get("n", "")),
                _fmt_p(p.get("p_value")),
                "Yes" if p.get("significant") else "No",
                p.get("strength", ""),
            ])
        story.append(_table(rows, [2.1 * inch, 0.5 * inch, 0.5 * inch, 0.7 * inch, 0.8 * inch, 0.9 * inch], ss))

        caveats = [p for p in pairs if p.get("caveat")]
        if caveats:
            story.append(Spacer(1, 8))
            for p in caveats:
                story.append(Paragraph(
                    f"{p.get('col1', '')} <-> {p.get('col2', '')}: {p['caveat']}", ss["Caveat"],
                ))

        vif_results = (cc.get("multicollinearity") or {}).get("results") or []
        if vif_results:
            story.append(Spacer(1, 12))
            story.append(Paragraph("Redundancy check (multicollinearity)", ss["Body"]))
            rows = [["Column", "VIF", "Severity", "Note"]]
            for v in vif_results:
                rows.append([v.get("column", ""), str(v.get("vif", "")), v.get("severity", ""), _cell(v.get("note", ""), ss)])
            story.append(_table(rows, [1.1 * inch, 0.6 * inch, 0.9 * inch, 2.9 * inch], ss))

    doc.build(story)
    return buf.getvalue()


def _fmt_p(p: Optional[float]) -> str:
    if p is None:
        return ""
    return "< 0.001" if p < 0.001 else f"{p:.3f}"
